# Generated by Django 3.0.7 on 2020-06-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerUtil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=60)),
                ('cpu_utilization', models.FloatField()),
                ('memory_utilization', models.FloatField()),
                ('disk_utilization', models.FloatField()),
            ],
        ),
    ]
